server:
  port: 5005
spring:
  application:
    name: job-portal-application-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/job_portal_application
    username: postgres
    password: Vi12sh@1234
    driver-class-name: org.postgresql.Driver