networks:
  job-portal-net:
    driver: bridge
services:
  userdb:
    image: postgres:16
    container_name: job-portal-userdb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: job_portal_user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - job-portal-net


  companydb:
    image: postgres:16
    container_name: job-portal-companydb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: job_portal_company
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - job-portal-net


  jobdb:
    image: postgres:16
    container_name: job-portal-jobdb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: job_portal_job
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - job-portal-net



  applicationdb:
    image: postgres:16
    container_name: job-portal-applicationdb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: job_portal_application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - job-portal-net


  preferencedb:
    image: postgres:16
    container_name: job-portal-preferencedb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: job_portal_preferencedb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - job-portal-net


  resumedb:
    image: postgres:16
    container_name: job-portal-resumedb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: job_portal_resumedb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - job-portal-net



# spring cloud
  discovery:
    image: vikasprajapatii/job-portal-service-registry:latest
    container_name: job-portal-discovery
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "8761:8761"
    networks:
      - job-portal-net

  config-server:
    image: vikasprajapatii/job-portal-config-server:latest
    volumes:
      - ../backend/config-repo:/config-repo
    container_name: job-portal-config-server
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      discovery:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - job-portal-net


  gateway:
    image: vikasprajapatii/job-portal-api-gateway:latest
    container_name: job-portal-gateway
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      config-server:
        condition: service_started
    command: ["--spring.config.import=configserver:http://config-server:8888"]
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - job-portal-net



  user-service:
    image: vikasprajapatii/job-portal-user-service:latest
    container_name: job-portal-user-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      discovery:
        condition: service_started
      userdb:
        condition: service_healthy
      config-server:
        condition: service_started
    command: ["--spring.config.import=configserver:http://config-server:8888"]
    environment:
      SPRING_CONFIG_SERVER_URL: http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:5432/job_portal_user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - job-portal-net



  company-service:
    image: vikasprajapatii/job-portal-company-service:latest
    container_name: job-portal-company-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      discovery:
        condition: service_started
      companydb:
        condition: service_healthy
      config-server:
        condition: service_started
    command: ["--spring.config.import=configserver:http://config-server:8888"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://companydb:5432/job_portal_company
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - job-portal-net

  job-service:
    image: vikasprajapatii/job-portal-job-service:latest
    container_name: job-portal-job-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5003:5003"
    depends_on:
      discovery:
        condition: service_started
      jobdb:
        condition: service_healthy
      config-server:
        condition: service_started
    command: ["--spring.config.import=configserver:http://config-server:8888"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://jobdb:5432/job_portal_job
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
      SPRING_REDIS_HOST: redis
    networks:
      - job-portal-net


  application-service:
    image: vikasprajapatii/job-portal-application-service:latest
    container_name: job-portal-application-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5004:5004"
    depends_on:
      discovery:
        condition: service_started
      applicationdb:
        condition: service_healthy
      config-server:
        condition: service_started
    command: ["--spring.config.import=configserver:http://config-server:8888"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://applicationdb:5432/job_portal_application
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - job-portal-net


  preference-service:
    image: vikasprajapatii/job-portal-preference-service:latest
    container_name: job-portal-preference-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5005:5005"
    depends_on:
      discovery:
        condition: service_started
      preferencedb:
        condition: service_healthy
      config-server:
        condition: service_started
    command: ["--spring.config.import=configserver:http://config-server:8888"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://preferencedb:5432/job_portal_preferencedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - job-portal-net


  resume-service:
    image: vikasprajapatii/job-portal-resume-service:latest
    container_name: job-portal-resume-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5009:5009"
    depends_on:
      discovery:
        condition: service_started
      resumedb:
        condition: service_healthy
      config-server:
        condition: service_started
    command: ["--spring.config.import=configserver:http://config-server:8888"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://resumedb:5432/job_portal_resumedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - job-portal-net


  ai-service:
    image: vikasprajapatii/job-portal-ai-service:latest
    container_name: job-portal-ai-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5010:5010"
    depends_on:
      discovery:
        condition: service_started
      config-server:
        condition: service_started
    command: ["--spring.config.import=configserver:http://config-server:8888"]
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - job-portal-net

  notification-service:
    image: vikasprajapatii/job-portal-notification-service:latest
    container_name: job-portal-notification-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    restart: always
    ports:
      - "5008:5008"
    depends_on:
      discovery:
        condition: service_started
      config-server:
        condition: service_started
    command: ["--spring.config.import=configserver:http://config-server:8888"]
    environment:
      SPRING_CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"
    networks:
      - job-portal-net

  redis:
    image: redis:7-alpine
    container_name: job-portal-redis
    ports:
      - "6379:6379"
    networks:
      - job-portal-net


