server:
  port: 5001
  forward-headers-strategy: framework
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job_portal_user
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:9000/login/oauth2/code/google"
            scope:
              - email
              - profile
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:placeholder@gmail.com}
    password: ${MAIL_PASSWORD:placeholder}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
