server:
  port: 5008

spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:vikaskumarprajapati8287@gmail.com}
    password: ${MAIL_PASSWORD:12345}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
